# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures
Vector is 1D array and Matrix is 2D array.

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [2]:
# To avoid overwriting the output, please code here 
list_1 = [1, 2, 3, 4, 5]
arr = np.array(list_1)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [3]:
# To avoid overwriting the output, please code here 
arr = np.arange(0, 6)
print(arr)

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [4]:
# To avoid overwriting the output, please code here 
zeros = np.zeros(5)
print(zeros)


[0. 0. 0. 0. 0.]


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [ ]:
# To avoid overwriting the output, please code here 


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [5]:
# To avoid overwriting the output, please code here 
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [7]:
# To avoid overwriting the output, please code here 
tens = np.ones(5) * 10
print(tens)

[10. 10. 10. 10. 10.]


array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [8]:
# To avoid overwriting the output, please code here 
even_nums = np.arange(52, 100, 2)
print(even_nums)


[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [3]:
# To avoid overwriting the output, please code here 
lin_arr = np.linspace(0, 1, 10)
step = lin_arr[1] - lin_arr[0]
print(lin_arr)
print("Step size:", step)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Step size: 0.1111111111111111


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [ ]:
# To avoid overwriting the output, please code here 
vec = np.arange(25)
print(vec)





[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
# To avoid overwriting the output, please code here 
matrix_2d = vec.reshape(5, 5)
print(matrix_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [6]:
# Using shape
# Using shape instead of reshape
vec.shape = (5, 5)
print(vec)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**12. Please generate the following matrix.**

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [29]:
# To avoid overwriting the output, please code here 

In [9]:
lin = np.linspace(0, 5, 10)
print(lin)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [32]:
# To avoid overwriting the output, please code here 

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [10]:
# To avoid overwriting the output, please code here 
rand_matrix = np.random.rand(7, 5)
print(rand_matrix)

[[0.24415287 0.37220561 0.54552741 0.60128318 0.00982725]
 [0.37671322 0.3376019  0.89332433 0.89083716 0.87800105]
 [0.72468555 0.75679058 0.18838565 0.43670242 0.60219163]
 [0.95332764 0.81001394 0.58838022 0.18147882 0.08128928]
 [0.94673087 0.93861904 0.33239458 0.82283704 0.63223551]
 [0.05564774 0.81149467 0.83658868 0.59681645 0.48015462]
 [0.68665394 0.44494332 0.78719044 0.09940047 0.65682996]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [36]:
# To avoid overwriting the output, please code here 

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 